#!/usr/bin/env python3
"""Initialize PostgreSQL and import the checked-in SQLite dataset once."""

import argparse
import os
import sqlite3
from contextlib import closing

import psycopg


DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "terraria.db")
SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    name TEXT PRIMARY KEY,
    item_id INTEGER,
    type TEXT,
    rarity TEXT,
    sell_copper INTEGER,
    research INTEGER
);

CREATE TABLE IF NOT EXISTS recipes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_name TEXT NOT NULL,
    result_amount INTEGER DEFAULT 1,
    station TEXT
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    recipe_id INTEGER NOT NULL REFERENCES recipes(id),
    ingredient_name TEXT NOT NULL,
    amount INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_recipes_result ON recipes(result_name);
CREATE INDEX IF NOT EXISTS idx_ingredients_recipe ON recipe_ingredients(recipe_id);
CREATE INDEX IF NOT EXISTS idx_ingredients_name ON recipe_ingredients(ingredient_name);

CREATE TABLE IF NOT EXISTS app_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""
MIGRATION_KEY = "sqlite_import_v1"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Replace existing application rows with the current SQLite dataset.",
    )
    args = parser.parse_args()

    if not os.path.isfile(DB_PATH):
        raise FileNotFoundError(f"SQLite source database not found: {DB_PATH}")

    with closing(sqlite3.connect(DB_PATH)) as sqlite_conn, psycopg.connect() as pg_conn:
        sqlite_conn.row_factory = sqlite3.Row
        with pg_conn.cursor() as cursor:
            for statement in SCHEMA.split(";"):
                if statement.strip():
                    cursor.execute(statement)
            cursor.execute(
                "SELECT value FROM app_metadata WHERE key = %s",
                (MIGRATION_KEY,),
            )
            already_imported = cursor.fetchone() is not None

            if already_imported and not args.replace:
                print("The SQLite dataset has already been imported; no changes made.")
                return

            if args.replace:
                cursor.execute("DELETE FROM recipe_ingredients")
                cursor.execute("DELETE FROM recipes")
                cursor.execute("DELETE FROM items")
                cursor.execute("DELETE FROM app_metadata WHERE key = %s", (MIGRATION_KEY,))
            else:
                cursor.execute(
                    "SELECT "
                    "(SELECT COUNT(*) FROM items) + "
                    "(SELECT COUNT(*) FROM recipes) + "
                    "(SELECT COUNT(*) FROM recipe_ingredients)"
                )
                if cursor.fetchone()[0]:
                    raise RuntimeError(
                        "PostgreSQL already contains data but has no SQLite import marker. "
                        "Use --replace only if replacing those rows is intended."
                    )

            cursor.executemany(
                "INSERT INTO items "
                "(name, item_id, type, rarity, sell_copper, research) "
                "VALUES (%s, %s, %s, %s, %s, %s)",
                [
                    tuple(row)
                    for row in sqlite_conn.execute(
                        "SELECT name, item_id, type, rarity, sell_copper, research FROM items"
                    )
                ],
            )
            cursor.executemany(
                "INSERT INTO recipes (id, result_name, result_amount, station) "
                "VALUES (%s, %s, %s, %s)",
                [
                    tuple(row)
                    for row in sqlite_conn.execute(
                        "SELECT id, result_name, result_amount, station FROM recipes"
                    )
                ],
            )
            cursor.executemany(
                "INSERT INTO recipe_ingredients (recipe_id, ingredient_name, amount) "
                "VALUES (%s, %s, %s)",
                [
                    tuple(row)
                    for row in sqlite_conn.execute(
                        "SELECT recipe_id, ingredient_name, amount FROM recipe_ingredients"
                    )
                ],
            )
            cursor.execute(
                "SELECT setval("
                "pg_get_serial_sequence('recipes', 'id'), "
                "(SELECT COALESCE(MAX(id), 1) FROM recipes), true)"
            )
            cursor.execute(
                "INSERT INTO app_metadata (key, value) VALUES (%s, %s)",
                (MIGRATION_KEY, "Imported terraria.db"),
            )

            cursor.execute(
                "SELECT "
                "(SELECT COUNT(*) FROM items), "
                "(SELECT COUNT(*) FROM recipes), "
                "(SELECT COUNT(*) FROM recipe_ingredients)"
            )
            item_count, recipe_count, ingredient_count = cursor.fetchone()

    print(
        "Imported PostgreSQL dataset: "
        f"{item_count} items, {recipe_count} recipes, "
        f"{ingredient_count} recipe ingredients."
    )


if __name__ == "__main__":
    main()
